framework:
    cache:
        # Redis
        app: cache.adapter.redis
        system: cache.adapter.redis
        default_redis_provider: snc_redis.cache
        pools:
            api_platform.cache:
                adapter: cache.adapter.redis