doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        metadata_cache_driver:
            type: service
            id: snc_redis.doctrine.metadata_cache
        query_cache_driver:
            type: service
            id: snc_redis.doctrine.query_cache
        result_cache_driver:
            type: service
            id: snc_redis.doctrine.result_cache
        second_level_cache:
            region_cache_driver:
                type: service
                id: snc_redis.doctrine.second_level_cache
            enabled: true
            region_lifetime: 86400
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
