knpu_oauth2_client:
    clients:
        azure:
            type: azure
            client_id: '%env(AZURE_CLIENT_ID)%'
            client_secret: '%env(AZURE_CLIENT_SECRET)%'
            api_version: 'v1.0'
            url_api: 'https://graph.microsoft.com/'
            redirect_route: oauth_check_azure