version: '3'
services:
  database:
    image: mariadb:10.1
    volumes:
      - .docker/data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: template
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - 3306:3306
    labels:
      com.symfony.server.service-prefix: 'DATABASE'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOSTS: database
      PMA_USER: root
      PMA_PASSWORD: toor
      UPLOAD_LIMIT: '20480000'
    ports:
      - 8080:80
    links:
      - database

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1025:1025
      - 1080:1080
    labels:
      com.symfony.server.service-prefix: 'MAILER'

  redis:
    image: redis
    volumes:
      - .docker/data/redis:/data
    ports:
      - 6379:6379
    labels:
      com.symfony.server.service-prefix: 'REDIS'
